CREATE DATABASE EMPRESA

USE EMPRESA

CREATE TABLE DEPARTAMENTO(
	CODDEPTO INTEGER NOT NULL IDENTITY(10,10),
	DEPTO VARCHAR(50) NOT NULL,
	RAMAL VARCHAR(5) NOT NULL,

	CONSTRAINT PKDEPARTAMENTO PRIMARY KEY (CODDEPTO)
)

CREATE TABLE EMPREGADO (
	CODEMPREGADO INTEGER NOT NULL IDENTITY(1,1), 
	NOME VARCHAR(250) NOT NULL, 
	TEL VARCHAR (25),
	CEL VARCHAR(50) NOT NULL,
	DTNASC DATE,
	DTADMISSAO DATE,
	ENDERECO VARCHAR(150) NOT NULL,
	BAIRRO VARCHAR(150),
	CIDADE VARCHAR(150),
	SALARIO FLOAT,
	CODDEPTO INTEGER NOT NULL,


	CONSTRAINT PKEMPREGADO PRIMARY KEY (CODEMPREGADO),
	CONSTRAINT FKDEPARTAMENTO FOREIGN KEY (CODDEPTO) REFERENCES DEPARTAMENTO(CODDEPTO)
)

CREATE TABLE DEPENDENTES(
	CODDEPENDENTE INTEGER NOT NULL IDENTITY(100,1),
	NOME_DEPENDENTE VARCHAR(250) NOT NULL,
	DTNASC_DEPENDENTE DATE,
	PARENTESCO VARCHAR(100) NOT NULL,
	CODEMPREGADO INTEGER NOT NULL,

	CONSTRAINT PKDEPENDENTES PRIMARY KEY (CODDEPENDENTE),
	CONSTRAINT FKEMPREGADO FOREIGN KEY (CODEMPREGADO) REFERENCES EMPREGADO (CODEMPREGADO)
)

INSERT INTO DEPARTAMENTO VALUES ('TI','0802')
INSERT INTO DEPARTAMENTO VALUES ('RH','0819')
INSERT INTO DEPARTAMENTO VALUES ('ADMINISTRAÇÃO','0822')
INSERT INTO DEPARTAMENTO VALUES ('CONTABILIDADE','0821')
INSERT INTO DEPARTAMENTO VALUES ('COMERCIAL','0810')

SELECT * FROM DEPARTAMENTO
SELECT * FROM EMPREGADO
SELECT * FROM DEPENDENTES

/*INSERT INTO EMPREGADO VALUES ('Elaine Cristina','','3198520-6624','22-01-1976','03/04/2009','Rua Santos Silva, 323','Ideal','Ipatinga',3.200,30)
DELETE
FROM EMPREGADO
WHERE CODEMPREGADO = 1
*/
INSERT INTO EMPREGADO VALUES ('Elaine Cristina','','3198520-6624','22-01-1976','03/04/2009','Rua Santos Silva, 323','Ideal','Ipatinga',3200,30)
INSERT INTO EMPREGADO VALUES ('Israel Rodolfo','3138269598','3199898-6894','24-11-1986','03/09/2012','Rua de Baixo, 33','Iguaçu','Ipatinga',2500,50)

INSERT INTO EMPREGADO VALUES ('Luzia Alves','3138228456','3198232-8954','12-11-1982','13/01/2015','Av Tulio Moreira, 03','Cariru','Timoteo',3100,20)
INSERT INTO EMPREGADO VALUES ('Ana Beatriz Morais','','31994598253','08-02-1997','12/12/2019','Rua Silvino Santos, 323','Ideal','Ipatinga',5500,10)
INSERT INTO EMPREGADO VALUES ('José Santos','','31988586956','04-12-1979','12/02/2016','Av Sal e Brasa, 78','Bom Retiro','Ipatinga',2700,40)

SELECT * FROM DEPARTAMENTO

SELECT * FROM EMPREGADO

SELECT * FROM DEPENDENTES

INSERT INTO DEPENDENTES VALUES ('Victor Emanuell','09/02/2009','FILHO',2)
INSERT INTO DEPENDENTES VALUES ('Heithor Eliezer','04/03/2008','NETO',4)
INSERT INTO DEPENDENTES VALUES ('João Gustavo','15/02/2015','FILHO',6)
INSERT INTO DEPENDENTES VALUES ('Maria','15/02/2015','FILHA',6)

INSERT INTO DEPENDENTES VALUES ('Marina Rodolfo','23/12/1992','Esposa',3)
INSERT INTO DEPENDENTES VALUES ('Lucas Rodolfo','19/04/2017','FILHO',3)


/*exercicios*/
--1
SELECT EMPREGADO.NOME, DEPENDENTES.NOME_DEPENDENTE, DEPENDENTES.PARENTESCO
FROM EMPREGADO INNER JOIN DEPENDENTES ON(EMPREGADO.CODEMPREGADO = DEPENDENTES.CODEMPREGADO)
ORDER BY EMPREGADO.NOME, DEPENDENTES.PARENTESCO

--2
SELECT EMPREGADO.NOME, EMPREGADO.TEL
FROM EMPREGADO INNER JOIN DEPARTAMENTO ON (DEPARTAMENTO.CODDEPTO = EMPREGADO.CODDEPTO)
ORDER BY DEPARTAMENTO.DEPTO, EMPREGADO.NOME

--3
SELECT EMPREGADO.NOME AS NOME_EMPREGADO, EMPREGADO.CIDADE, DEPENDENTES.NOME_DEPENDENTE, DEPENDENTES.DTNASC_DEPENDENTE, DEPENDENTES.PARENTESCO
FROM EMPREGADO INNER JOIN DEPENDENTES ON (EMPREGADO.CODEMPREGADO = DEPENDENTES.CODEMPREGADO)
ORDER BY EMPREGADO.CIDADE

--4
SELECT DEPARTAMENTO.DEPTO AS NOME_DEPARTAMENTO, EMPREGADO.NOME AS NOME_EMPREGADO
FROM DEPARTAMENTO INNER JOIN EMPREGADO ON (DEPARTAMENTO.CODDEPTO = EMPREGADO.CODDEPTO)
WHERE EMPREGADO.SALARIO >= 6000
ORDER BY EMPREGADO.SALARIO DESC

--5
SELECT NOME, DTNASC
FROM EMPREGADO
ORDER BY DTNASC DESC

--6
SELECT EMPREGADO.NOME, EMPREGADO.TEL, DEPARTAMENTO.DEPTO AS NOME_DEPARTAMENTO, DEPARTAMENTO.RAMAL
FROM DEPARTAMENTO INNER JOIN EMPREGADO ON (DEPARTAMENTO.CODDEPTO = EMPREGADO.CODDEPTO)
ORDER BY DEPARTAMENTO.DEPTO, EMPREGADO.TEL, EMPREGADO.NOME

--7
SELECT SUM(SALARIO) AS TOTAL_SALARIO
FROM EMPREGADO

--8
SELECT AVG(SALARIO) AS MEDIA_SALARIO
FROM EMPREGADO

--9
SELECT EMPREGADO.NOME AS NOME_EMPREGADO, DEPENDENTES.NOME_DEPENDENTE
FROM DEPARTAMENTO INNER JOIN EMPREGADO ON (DEPARTAMENTO.CODDEPTO = EMPREGADO.CODDEPTO)
	INNER JOIN DEPENDENTES ON (DEPENDENTES.CODEMPREGADO = EMPREGADO.CODEMPREGADO)
ORDER BY DEPARTAMENTO.DEPTO, EMPREGADO.NOME, DEPENDENTES.NOME_DEPENDENTE

--10
SELECT *
FROM DEPARTAMENTO
ORDER BY DEPTO DESC

--11
SELECT SUM(EMPREGADO.SALARIO) AS TOTAL_SALARIO_DEPARTAMENTO, DEPARTAMENTO.DEPTO
FROM DEPARTAMENTO INNER JOIN EMPREGADO ON (DEPARTAMENTO.CODDEPTO = EMPREGADO.CODDEPTO)
GROUP BY DEPARTAMENTO.DEPTO

--12
SELECT *
FROM EMPREGADO
WHERE DAY(DTNASC) = 29 AND MONTH(DTNASC) = 2
ORDER BY DTNASC DESC

--13
SELECT COUNT(*)
FROM EMPREGADO

--14
SELECT COUNT(A.CODDEPTO) AS QUANTIDADE_EMPREGADOS_POR_DPTO, A.DEPTO
FROM DEPARTAMENTO A INNER JOIN EMPREGADO B ON(A.CODDEPTO = B.CODDEPTO)
GROUP BY A.DEPTO

--15
SELECT COUNT(B.NOME_DEPENDENTE) AS TOTAL_DE_DEPENDENTES, A.NOME
FROM EMPREGADO A INNER JOIN DEPENDENTES B ON (A.CODEMPREGADO = B.CODEMPREGADO)
GROUP BY A.NOME

SELECT * FROM EMPREGADO
SELECT * FROM DEPENDENTES

--16
SELECT DEPENDENTES.NOME_DEPENDENTE, DEPENDENTES.PARENTESCO, EMPREGADO.NOME AS NOME_EMPREGADOS
FROM EMPREGADO INNER JOIN DEPENDENTES ON (EMPREGADO.CODEMPREGADO = DEPENDENTES.CODEMPREGADO)
ORDER BY DEPENDENTES.PARENTESCO

--17
SELECT DEPENDENTES.NOME_DEPENDENTE, DEPENDENTES.PARENTESCO, EMPREGADO.NOME AS NOME_EMPREGADOS, EMPREGADO.DTNASC
FROM EMPREGADO INNER JOIN DEPENDENTES ON (EMPREGADO.CODEMPREGADO = DEPENDENTES.CODEMPREGADO)
ORDER BY EMPREGADO.DTNASC

--18
SELECT MIN(EMPREGADO.SALARIO), DEPARTAMENTO.DEPTO
FROM DEPARTAMENTO FULL JOIN EMPREGADO ON (DEPARTAMENTO.CODDEPTO = EMPREGADO.CODDEPTO)
GROUP BY DEPARTAMENTO.DEPTO

--19
SELECT NOME
FROM EMPREGADO
WHERE NOME NOT LIKE '%SOUZA'

--20
SELECT DEPARTAMENTO.DEPTO, EMPREGADO.NOME
FROM DEPARTAMENTO INNER JOIN EMPREGADO ON (DEPARTAMENTO.CODDEPTO = EMPREGADO.CODDEPTO)
WHERE DEPARTAMENTO.DEPTO LIKE '%TI'


--21
SELECT NOME
FROM EMPREGADO
WHERE CIDADE = 'RECIFE' AND SALARIO > 10000

--22
SELECT EMPREGADO.NOME, DEPARTAMENTO.DEPTO
FROM DEPARTAMENTO INNER JOIN EMPREGADO ON (DEPARTAMENTO.CODDEPTO = EMPREGADO.CODDEPTO)
WHERE DEPARTAMENTO.DEPTO = 'PESSOAL'

--23
SELECT NOME
FROM EMPREGADO
WHERE MONTH(DTNASC) = 10